version: '3.1'

services:

  lora-mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - lora
  lora-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: ${LORA_GATEWAY_DB_CONNECTION_STRING}
    networks:
      - lora
  lora-rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "lora-rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"
    networks:
      - lora
  lora-gateway:
    image: "lora-gateway"
    build:
      context: .
      dockerfile: dockerfiles/gateway/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
       - LORA_GATEWAY_DB_CONNECTION_STRING=${LORA_GATEWAY_DB_CONNECTION_STRING}
       - LORA_GATEWAY_DB_DATABASE_NAME=${LORA_GATEWAY_DB_DATABASE_NAME}
       - LORA_GATEWAY_DEVECE_COLLECTION_NAME=${LORA_GATEWAY_DEVECE_COLLECTION_NAME}
       - LORA_GATEWAY_MQ_HOST_NAME=${LORA_GATEWAY_MQ_HOST_NAME}
       - LORA_GATEWAY_MQ_ROUTING_KEY=${LORA_GATEWAY_MQ_ROUTING_KEY}
       - LORA_GATEWAY_MQ_USER_NAME=${LORA_GATEWAY_MQ_USER_NAME}
       - LORA_GATEWAY_MQ_PASSWORD=${LORA_GATEWAY_MQ_PASSWORD}
       - LORA_GATEWAY_MQ_PORT=${LORA_GATEWAY_MQ_PORT}
       - LOG_FILE_PATH=${LOG_FILE_PATH}
    expose:
      - "80"
    ports:
      - "${LORA_INTEGRATION_PORT}:80"
    container_name: lora-gateway
    hostname: lora-gateway
    depends_on:
      lora-mongo:
        condition: service_started
      lora-rabbitmq:
        condition: service_started
    networks:
      - lora
  iot-home:
    image: "iot-home"
    build:
      context: .
      dockerfile: dockerfiles/listener/Dockerfile
    environment:
       - EMAIL_SENDER_API_KEY=${EMAIL_SENDER_API_KEY}
       - EMAIL_SENDER_FROM_EMAIL=${EMAIL_SENDER_FROM_EMAIL}
       - EMAIL_SENDER_FROM_NAME_EMAIL=${EMAIL_SENDER_FROM_NAME_EMAIL}
       - LORA_GATEWAY_MQ_HOST_NAME=${LORA_GATEWAY_MQ_HOST_NAME}
       - LORA_GATEWAY_MQ_ROUTING_KEY=${LORA_GATEWAY_MQ_ROUTING_KEY}
       - LORA_GATEWAY_MQ_USER_NAME=${LORA_GATEWAY_MQ_USER_NAME}
       - LORA_GATEWAY_MQ_PASSWORD=${LORA_GATEWAY_MQ_PASSWORD}
       - LORA_GATEWAY_MQ_PORT=${LORA_GATEWAY_MQ_PORT}
    container_name: iot-home
    hostname: iot-home
    depends_on:
      lora-mongo:
        condition: service_started
      lora-rabbitmq:
        condition: service_started
      lora-gateway:
        condition: service_started
    networks:
      - lora
networks:
  lora: